---
- hosts: localhost-py3
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes cache_valid_time=3600 force_apt_get=yes

    - name: Install pip
      apt: name=python3-pip state=present

    - name: Install pytest
      pip: name=pytest

    - name: Install pytest-base-url
      pip: name=pytest-base-url

    - name: Install docker-py package
      pip: name=docker-py

    - name: Run the test and get the result
      command: pytest pytest_url.py --tb=no --no-header
      register: pytest_result
      ignore_errors: yes

    - name: Build Docker image from Dockerfile
      docker_image:
        name: webapp_docker
        build:
          path: docker
        source: build
      when: pytest_result is failed

    - name: Running the container
      docker_container:
        name: mywebapp
        image: webapp_docker:latest
        ports:
          - "8080:8080"
      when: pytest_result is failed

    - name: Show message if container exists
      debug:     
        msg: The container already exists.
      when: pytest_result is succeeded
